spring.application.name=film_rental_store



spring.datasource.url=jdbc:mysql://10.30.74.48:3306/sakila
spring.datasource.username=testuser
spring.datasource.password=saniya123




# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Server
server.port=8081

# Security (temporary basic login)
spring.security.user.name=admin
spring.security.user.password=admin